version: "3"
services:
  flame-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - flame-pg-data:/var/lib/postgres
    networks:
      - flame-network

  flame-redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - flame-redis-data:/data
    networks:
      - flame-network

networks:
  flame-network:
    driver: bridge
volumes:
  flame-pg-data:
  flame-redis-data:
  node_modules:
