CREATE TABLE accounts (
  id UUID PRIMARY KEY,
  username VARCHAR UNIQUE,
  email TEXT UNIQUE NOT NULL,
  completed_account BOOLEAN NOT NULL DEFAULT FALSE,
  confirmed_email BOOLEAN NOT NULL DEFAULT FALSE

);

